apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mttl-exam-app
  namespace: argocd 

  # Add a this finalizer ONLY if you want these to cascade delete.
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  # The project the application belongs to.
  project: default

  # Source of the application manifests
  source:
    repoURL: git@github.com:sirawatyodpram/mttl-exam.git
    targetRevision: development
    path: go-app/helm

  # Destination cluster and namespace to deploy the application
  destination:
    server: https://kubernetes.default.svc
    namespace: exam
    
  # Sync policy
  syncPolicy:
    automated:
      prune: false # Specifies if resources should be pruned during auto-syncing ( false by default ).
      selfHeal: true # Specifies if partial app sync should be executed when resources are changed only in target Kubernetes cluster and no git change detected ( false by default ).
    syncOptions:
        - CreateNamespace=true
        - ApplyOutOfSyncOnly=true
        - PruneLast=true
